markdown: kramdown

encoding: utf-8

gems: [jekyll-paginate,jekyll-sitemap]

paginate: 20
paginate_path: "page:num"

default_language: zh-cn

simple_food:
  favicon_navbar:
  favicon_footer:

  theme: default

